#!/command/with-contenv bash
# shellcheck shell=bash
#####################################
# All rights reserved.              #
# started from Zero                 #
# Docker owned dockserver           #
# Docker Maintainer dockserver      #
#####################################
#####################################
# THIS DOCKER IS UNDER LICENSE      #
# NO CUSTOMIZING IS ALLOWED         #
# NO REBRANDING IS ALLOWED          #
# NO CODE MIRRORING IS ALLOWED      #
#####################################
function log() {
     echo "${1}"
}

addgroup -S abc &>/dev/null
adduser -S abc -G abc &>/dev/null
PGID=${PGID:-1000}
PUID=${PUID:-1000}
groupmod -o -g "$PGID" abc &>/dev/null
usermod -o -u "$PUID" abc &>/dev/null

if [[ -f /donate.txt ]]; then
   cat /donate.txt
fi
echo '
-------------------------------------
GID/UID
-------------------------------------'
echo "
User uid:    $(id -u abc)
User gid:    $(id -g abc)
-------------------------------------
"
   cat > /etc/apk/repositories << EOF; $(echo)
http://dl-cdn.alpinelinux.org/alpine/v$(cat /etc/alpine-release | cut -d'.' -f1,2)/main
http://dl-cdn.alpinelinux.org/alpine/v$(cat /etc/alpine-release | cut -d'.' -f1,2)/community
http://dl-cdn.alpinelinux.org/alpine/edge/testing
EOF

   apk --quiet --no-progress update && \
   apk --quiet --no-progress upgrade

   cat /app/requirements.txt | while IFS=$'\n' read -ra myArray; do
      apk add --quiet --no-progress --update ${myArray[@]}
   done

   wget -qO- https://rclone.org/install.sh | bash &>/dev/null

   KEYLOCAL=/system/servicekeys/keys/
   ARRAY=$(ls -A ${KEYLOCAL} | wc -w )
   if [[ "${ARRAY}" -eq "0" ]]; then
      log "-->> [ WARNING ] ----------------- [ WARNING ] <<--"
      log "-->> [ WARNING ]  no match found   [ WARNING ] <<--"
      log "-->> [ WARNING ]  of GDSA[01=~100] [ WARNING ] <<--"
      log "-->> [ WARNING ]    or [01=~100]   [ WARNING ] <<--"
      log "-->> [ WARNING ] ----------------- [ WARNING ] <<--"
      sleep infinity
   fi

  cp -r /conf/nginx.conf /etc/nginx/nginx.conf
  cp -r /conf/fpm-pool.conf /etc/php8/php-fpm.d/www.conf
  cp -r /conf/php.j2 /etc/php8/conf.d/custom.ini

  rm -rf /system/uploader/.keys/{usedupload,lastday} \
         /app/uploader/{pid,discord} \
         /system/uploader/vfsforget &>/dev/null

  mkdir -p /system/uploader/.keys \
           /system/uploader/{logs,json} \
           /system/uploader/json/{done,upload} &>/dev/null

  apk add --quiet --no-progress --update coreutils
  find /mnt/downloads -type f -name '*.lck' -delete
  mkdir -p /root/.config/rclone/
  chown -cR abc:abc /root/.config/rclone /app /system/* &>/dev/null
  chmod -cR 755 /root/.config/rclone/ /app /system/* &>/dev/null
  chown -cR abc:abc /root/.config/ &>/dev/null

  USERAGENT=${USERAGENT:-null}
  if [[ ${USERAGENT} == 'null' ]]; then
     USERAGENT=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1)
  fi

  sample=/app/uploader/.sample.uploader.env
  uploaderenv=/system/uploader/uploader.env
  if [[ -f ${uploaderenv} ]]; then
source $uploaderenv
echo -e "#-------------------------------------------------------
#   UPLOADER ENVIROMENTS
#-------------------------------------------------------
## USER VALUES
PUID=${PUID:-1000}
PGID=${PGID:-1000}

## RCLONE - SETTINGS
BANDWITHLIMIT=${BANDWITHLIMIT:-40}
LOG_LEVEL=${LOG_LEVEL:-INFO}
DLFOLDER=${DLFOLDER:-/mnt/downloads}
USERAGENT=${USERAGENT}

## USER - SETTINGS
DRIVEUSEDSPACE=${DRIVEUSEDSPACE:-10}
MIN_AGE_FILE=${MIN_AGE_FILE:-10m}
#-------------------------------------------------------
#   UPLOADER ENVIROMENTS
#-------------------------------------------------------" >$uploaderenv
else
source $sample
echo -e "#-------------------------------------------------------
#   UPLOADER ENVIROMENTS
#-------------------------------------------------------
## USER VALUES
PUID=${PUID:-1000}
PGID=${PGID:-1000}

## RCLONE - SETTINGS
BANDWITHLIMIT=${BANDWITHLIMIT:-40}
LOG_LEVEL=${LOG_LEVEL:-INFO}
DLFOLDER=${DLFOLDER:-/mnt/downloads}
USERAGENT=${USERAGENT}

## USER - SETTINGS
DRIVEUSEDSPACE=${DRIVEUSEDSPACE:-10}
MIN_AGE_FILE=${MIN_AGE_FILE:-10m}
#-------------------------------------------------------
#   UPLOADER ENVIROMENTS
#-------------------------------------------------------" >$uploaderenv
fi

echo "------------------------------
    _____   _   _  __  __
   |_   _| | | | | \ \/ /
     | |   | |_| |  \  / 
     | |   |  _  |  /  \ 
     |_|   |_| |_| /_/\_\

------------------------------
     to all the coders

We have take some code from :

  88lex , RTRO , edrock200
 ChaoticWeg & linuxserver.io

       and all other
  If we missed you, sorry..

------------------------------"
