#!/command/with-contenv bash
# shellcheck shell=bash
#####################################
# All rights reserved.              #
# started from Zero                 #
# Docker owned dockserver           #
# Docker Maintainer dockserver      #
#####################################
#####################################
# THIS DOCKER IS UNDER LICENSE      #
# NO CUSTOMIZING IS ALLOWED         #
# NO REBRANDING IS ALLOWED          #
# NO CODE MIRRORING IS ALLOWED      #
#####################################
function log() {
     echo "${1}"
}

addgroup -S abc &>/dev/null
adduser -S abc -G abc &>/dev/null
PGID=${PGID:-1000}
PUID=${PUID:-1000}
groupmod -o -g "$PGID" abc &>/dev/null
usermod -o -u "$PUID" abc &>/dev/null

if [[ -f /donate.txt ]]; then
   $(which cat) /donate.txt
fi
echo '
-------------------------------------
GID/UID
-------------------------------------'
echo "
User uid:    $(id -u abc)
User gid:    $(id -g abc)
-------------------------------------
"
   $(which cat) > /etc/apk/repositories << EOF; $(echo)
http://dl-cdn.alpinelinux.org/alpine/v$(cat /etc/alpine-release | cut -d'.' -f1,2)/main
http://dl-cdn.alpinelinux.org/alpine/v$(cat /etc/alpine-release | cut -d'.' -f1,2)/community
http://dl-cdn.alpinelinux.org/alpine/edge/testing
EOF

   log "**** update packages ****"
   $(which apk) --quiet --no-progress update && \
   $(which apk) --quiet --no-progress upgrade

   log "**** install build packages ****"
   $(which cat) /app/requirements.txt | while IFS=$'\n' read -ra myArray; do
      $(which apk) add --quiet --no-progress --update ${myArray[@]}
   done

   log "**** install rclone ****" && \
   $(which wget) -qO- https://rclone.org/install.sh | bash &>/dev/null

   KEYLOCAL=/system/servicekeys/keys/
   ARRAY=$(ls ${KEYLOCAL} | wc -l )
   if [[ "${ARRAY}" -eq "0" ]]; then
      log "-->> [ WARNING ] ----------------- [ WARNING ] <<--"
      log "-->> [ WARNING ]  no match found   [ WARNING ] <<--"
      log "-->> [ WARNING ]  of GDSA[01=~100] [ WARNING ] <<--"
      log "-->> [ WARNING ]    or [01=~100]   [ WARNING ] <<--"
      log "-->> [ WARNING ] ----------------- [ WARNING ] <<--"
      sleep infinity
   fi

   log "**** copy dependencies ****"
   $(which cp) -r /conf/nginx.conf /etc/nginx/nginx.conf
   $(which cp) -r /conf/fpm-pool.conf /etc/php8/php-fpm.d/www.conf
   $(which cp) -r /conf/php.j2 /etc/php8/conf.d/custom.ini

   $(which rm) -rf /system/uploader/.keys/{usedupload,lastday} \
          /app/uploader/{pid,discord} \
          /system/uploader/vfsforget \
          /var/cache/apk/* &>/dev/null

   log "**** creating folders ****"
   $(which mkdir) -p /system/uploader/.keys \
           /system/uploader/{logs,json,sample} \
           /system/uploader/json/{done,upload} \
           /root/.config/rclone/ &>/dev/null

   ## COPY SAMPLE FILES ###
   $(which cp) -r /conf/crypt_multi_tdrive-example.csv /system/uploader/sample/crypt_multi_tdrive-example.csv
   $(which cp) -r /conf/uncrypt_multi_tdrive-example.csv /system/uploader/sample/uncrypt_multi_tdrive-example.csv

   ## SET PERMS ##
   $(which chown) -cR abc:abc /root/.config /app /system/* &>/dev/null
   $(which chmod) -cR 755 /root/.config/rclone/ /app /system/* &>/dev/null

   sample=/app/uploader/.sample.uploader.env
   uploaderenv=/system/uploader/uploader.env

   if test -f ${uploaderenv} ; then
     source $uploaderenv
   else
     source $sample
   fi

echo -e "#-------------------------------------------------------
#   UPLOADER ENVIROMENTS
#-------------------------------------------------------
## USER VALUES
PUID=${PUID:-1000}
PGID=${PGID:-1000}

## RCLONE - SETTINGS
BANDWITHLIMIT=${BANDWITHLIMIT:-40}
LOG_LEVEL=${LOG_LEVEL:-INFO}
DLFOLDER=${DLFOLDER:-/mnt/downloads}
TRANSFERS=${TRANSFERS:-2}

## USER - SETTINGS
DRIVEUSEDSPACE=${DRIVEUSEDSPACE:-10}

#-------------------------------------------------------
#   UPLOADER ENVIROMENTS
#-------------------------------------------------------" >$uploaderenv

echo "------------------------------
    _____   _   _  __  __
   |_   _| | | | | \ \/ /
     | |   | |_| |  \  / 
     | |   |  _  |  /  \ 
     |_|   |_| |_| /_/\_\

------------------------------
     to all the coders

We have take some code from :

  88lex , RTRO , edrock200
 ChaoticWeg & linuxserver.io

       and all other
  If we missed you, sorry..

------------------------------"
