#!/command/with-contenv bash
# shellcheck shell=bash

# Copyright (c) 2020, MrDoob
# All rights reserved.

# shellcheck disable=SC2086
umask 022
phpfpm_command="php-fpm8 -F"
echo "-> Starting php-fpm <-"
chmod -v 1777 /tmp /var/tmp &>/dev/null
exec s6-setuidgid root php-fpm8 -F
