#!/bin/bash
####################################
# All rights reserved.              #
# started from Zero                 #
# Docker owned dockserver           #
# Docker Maintainer dockserver      #
#####################################
#####################################
# THIS DOCKER IS UNDER LICENSE      #
# NO CUSTOMIZING IS ALLOWED         #
# NO REBRANDING IS ALLOWED          #
# NO CODE MIRRORING IS ALLOWED      #
#####################################
# shellcheck disable=SC2086
# shellcheck disable=SC2046

FOLDER=$1
APP=$2
USERNAME=$3
TOKEN=$4

### APP SETTINGS ###

APPBRANCH="master"
APPLINK="https://api.github.com/repos/darkalfx/requestrr"
NEWVERSION=$(curl -u $USERNAME:$TOKEN -sX GET "https://api.github.com/repos/darkalfx/requestrr/releases/latest" | jq -r '.tag_name')
NEWVERSION="${NEWVERSION#*v}"
NEWVERSION="${NEWVERSION#*release-}"
NEWVERSION="${NEWVERSION}"

HEADLINE="$(cat ./.templates/headline.txt)"
DESCRIPTION="$(curl -u $USERNAME:$TOKEN -sX GET "$APPLINK" | jq -r '.description')"

BASEIMAGE="ghcr.io/linuxserver/baseimage-ubuntu:focal"
URL="https://github.com/darkalfx/requestrr/releases/download"

INSTCOMMAND="apt-get install -yqq"
UPTCOMMAND="apt-get update -yqq"

PACKAGES="libicu66 unzip jq curl aria2 software-properties-common gpg-agent"
APPSPEC="unzip -q /tmp/requestrr.zip -d /tmp/requestrr && \\
    mkdir -p /app/requestrr/bin/ && \\
    mv /tmp/requestrr/requestrr-linux-x64/* /app/requestrr/bin/ && \\
    chmod +x /app/requestrr/bin/Requestrr.WebApi"

CLEANUP="apt-get remove -yqq aria2 jq software-properties-common gpg-agent && \\
    apt-get autoremove -yqq && apt-get clean -yqq && \\
    rm -rf /tmp/* /var/lib/apt/lists/* /var/tmp/*"

PICTURE="./images/$APP.png"
APPFOLDER="./$FOLDER/$APP"
PORT="EXPOSE 4545"
VOLUMEN="VOLUME /config"

### RELEASE SETTINGS ###

echo '{
   "appname": "'${APP}'",
   "apppic": "'${PICTURE}'",
   "appfolder": "./'$FOLDER'/'$APP'",
   "newversion": "'${NEWVERSION}'",
   "appbranch": "'${APPBRANCH}'",
   "baseimage": "'${BASEIMAGE}'",
   "description": "'${DESCRIPTION}'",
   "body": "Upgrading '${APP}' to '${NEWVERSION}'",
   "user": "github-actions[bot]"
}' > "./$FOLDER/$APP/release.json"

### DOCKER BUILD ###
### GENERATE Dockerfile based on release.json

echo '## This file is automatically generated (based on release.json)
##
## Do not changes any lines here
##
'"${HEADLINE}"'
FROM '"${BASEIMAGE}"'

ARG TARGETPLATFORM
ARG BUILDPLATFORM
ARG VERSION="'"${NEWVERSION}"'"
ARG BRANCH="'"${APPBRANCH}"'"
ARG DEBIAN_FRONTEND="'"noninteractive"'"

ENV XDG_CONFIG_HOME="'"/config/xdg"'"

RUN  \
  echo "'"**** add repositories ****"'" && \
    '"${UPTCOMMAND}"' && \
  echo "'"**** install packages ****"'" && \
    '"${INSTCOMMAND}"' '"${PACKAGES}"' && \
    aria2c -d /tmp -o requestrr.zip "'"${URL}/"'${VERSION}'"/requestrr-linux-x64.zip"'" && \
    '"${APPSPEC}"' && \
  echo "'"**** cleanup ****"'" && \
    '"${CLEANUP}"'

COPY '"${APPFOLDER}"'/root/ /
'"${PORT}"'
'"${VOLUMEN}"'
##EOF' > ./$FOLDER/$APP/Dockerfile
