#!/command/with-contenv bash
#####################################
# All rights reserved.              #
# started from Zero                 #
# Docker owned dockserver           #
# Docker Maintainer dockserver      #
#####################################
#####################################
# THIS DOCKER IS UNDER LICENSE      #
# NO CUSTOMIZING IS ALLOWED         #
# NO REBRANDING IS ALLOWED          #
# NO CODE MIRRORING IS ALLOWED      #
#####################################
umask 022

chown -cR abc:abc \
     /root \
     /app \
     /system &>/dev/null

chmod -cR 755 \
     /root \
     /app \
     /system &>/dev/null

command="/app/uploader/uploader.sh"

APP="$(basename -- $(for i in $(ls -d /app/*/); do echo ${i%%/}; done))"
if [[ -d "/mnt/unionfs" ]]; then
   while [ -z "`ls /mnt/unionfs`" ]
   do
      echo "wait mount /mnt/unionfs" && sleep 10
   done
   echo "mount working! $APP starting..."
fi

echo "-> Starting Multi Thread Uploader <-"
exec $command >/dev/null 2>&1
