#!/usr/bin/with-contenv bash

addgroup -S abc &>/dev/null
adduser -S abc -G abc &>/dev/null
PGID=${PGID:-1000}
PUID=${PUID:-1000}
groupmod -o -g "$PGID" abc &>/dev/null
usermod -o -u "$PUID" abc &>/dev/null

if [[ -f /donate.txt ]]; then
   $(which cat) /donate.txt
fi

$(which echo) '
-------------------------------------
GID/UID
-------------------------------------'
echo "
User uid:    $(id -u abc)
User gid:    $(id -g abc)
-------------------------------------
"

cat > /etc/apk/repositories << EOF; $(echo)
http://dl-cdn.alpinelinux.org/alpine/v3.15/main
http://dl-cdn.alpinelinux.org/alpine/v3.15/community
http://dl-cdn.alpinelinux.org/alpine/edge/testing
EOF

MAP=$(ls -1p /app/ | grep '/$' | $(command -v sed) 's/\/$//')

[[ -e /config/$MAP.pid ]] && \
    rm -rf /config/$MAP.pid

if [[ ! -f "/app/$MAP/donecerts" ]]; then
    echo "*** Running mono cert sync ***"
    apk update --quiet
    apk add --quiet --no-cache openssl
    apk add --quiet --no-cache ca-certificates
    apk add --no-cache mono --repository http://dl-cdn.alpinelinux.org/alpine/edge/testing
    cert-sync --quiet /etc/ssl/certs/ca-certificates.crt
    touch "/app/$MAP/donecerts"
fi

[[ -d /config/custom-cont-init.d ]] && \
  rm -rf /config/custom-cont-init.d

[[ -d /config/custom-services.d ]] && \
  rm -rf /config/custom-services.d

# permissions
chown -R abc:abc /config
