#!/usr/bin/with-contenv bash

echo "checking mount"

APP="$HOSTNAME"
if [[ -d "/mnt/unionfs" ]]; then
   while [ -z "`ls /mnt/unionfs`" ]
   do
      echo "wait mount /mnt/unionfs" && sleep 10
   done
   echo "mount working! $APP starting..."
   echo "Starting $APP."
fi

### Show plex Server name
GRAY="\033[0;37m"
BLUE="\033[0;34m"
NC="\033[0m"

PREFNAME="/config/Library/Application Support/Plex Media Server/Preferences.xml"
PlexName=$(sed -n "s/^.*FriendlyName=\"\([^\"]*\)\".*$/\1/p" "${PREFNAME}")
$(which echo) -e "${GRAY}[$($(which date) +'%Y/%m/%d %H:%M:%S')] Plex Media Server ${BLUE} ${PlexName} ${NC} (you can ignore the libusb_init error)"

###

export PLEX_MEDIA_SERVER_INFO_MODEL=$(uname -m)
export PLEX_MEDIA_SERVER_INFO_PLATFORM_VERSION=$(uname -r)

exec \
   s6-setuidgid abc \
   /usr/lib/plexmediaserver/Plex\ Media\ Server
