#!/usr/bin/with-contenv bash

PUID=${PUID:-911}
PGID=${PGID:-911}

groupmod -o -g "$PGID" abc
usermod -o -u "$PUID" abc

echo "----------------------------------------------------

 ____             _                                 
|  _ \  ___   ___| | _____  ___ _ ____   _____ _ __ 
| | | |/ _ \ / __| |/ / __|/ _ \ '__\ \ / / _ \ '__|
| |_| | (_) | (__|   <\__ \  __/ |   \ V /  __/ |   
|____/ \___/ \___|_|\_\___/\___|_|    \_/ \___|_|

----------------------------------------------------"
if [[ -f /donate.txt ]]; then
    echo '
To support the app dev(s) visit:'
    cat /donate.txt
fi
echo '
-------------------------------------
GID/UID
-------------------------------------'
echo "
User uid:    $(id -u abc)
User gid:    $(id -g abc)
-------------------------------------
"

chown abc:abc /app
chown abc:abc /config
chown abc:abc /defaults
chown abc:abc /system

