#!/usr/bin/env bash
# shellcheck shell=bash
#####################################
# All rights reserved.              #
# started from Zero                 #
# Docker owned dockserver           #
# Docker Maintainer dockserver      #
#####################################
#####################################
# THIS DOCKER IS UNDER LICENSE      #
# NO CUSTOMIZING IS ALLOWED         #
# NO REBRANDING IS ALLOWED          #
# NO CODE MIRRORING IS ALLOWED      #
#####################################

apt-get install --no-install-recommends -yqq git &>/dev/null

# Absolute-Series-Scanner
scannerdir="/config/Library/Application Support/Plex Media Server/Scanners/Series"
mkdir -p "$scannerdir"
  git clone --depth 1 https://github.com/ZeroQI/Absolute-Series-Scanner /tmp/absolute &>/dev/null && \
  cp -f "/tmp/absolute/Scanners/Series/Absolute Series Scanner.py" "$scannerdir/Absolute Series Scanner.py"
rm -rf /config/absolute /tmp/absolute &>/dev/null

# HAMA
plugindir="/config/Library/Application Support/Plex Media Server/Plug-ins"
chown -R abc:abc "$plugindir"
if [ ! -d "$plugindir/Hama.bundle" ]; then
    git clone --depth 1 https://github.com/ZeroQI/Hama.bundle "$plugindir/Hama.bundle" &>/dev/null
    chown -R abc:abc "$plugindir/Hama.bundle" &>/dev/null
else
    git -C "$plugindir/Hama.bundle" pull &>/dev/null
    chown -R abc:abc "$plugindir/Hama.bundle" &>/dev/null
fi

chown -R abc:abc "$plugindir" "$scannerdir" &>/dev/null

#E-o-L#
