#!/bin/bash
####################################
# All rights reserved.              #
# started from Zero                 #
# Docker owned dockserver           #
# Docker Maintainer dockserver      #
#####################################
#####################################
# THIS DOCKER IS UNDER LICENSE      #
# NO CUSTOMIZING IS ALLOWED         #
# NO REBRANDING IS ALLOWED          #
# NO CODE MIRRORING IS ALLOWED      #
#####################################
# shellcheck disable=SC2086
# shellcheck disable=SC2046

FOLDER=$1
APP=$2
USERNAME=$3
TOKEN=$4

### APP SETTINGS ###

APPBRANCH="master"
APPLINK="https://github.com/MediaBrowser/Emby"
NEWVERSION=$(curl -u $USERNAME:TOKEN -sX GET https://api.github.com/repos/MediaBrowser/Emby.Releases/releases/latest | jq --raw-output '. | .tag_name')
NEWVERSION="${NEWVERSION#*v}"
NEWVERSION="${NEWVERSION#*release-}"
NEWVERSION="${NEWVERSION}"

HEADLINE="$(cat ./.templates/headline.txt)"

DESCRIPTION="Docker Container for Emby Server"
BASESTAGE="ghcr.io/linuxserver/baseimage-ubuntu:bionic as buildstage"
INSTCOMMAND="apt-get install -yqq"
UPTCOMMAND="apt-get update -yqq"

## BUILDSTAGE

BUILDSTAGE="--from=buildstage /app/emby /app/emby"
EMBY_URL="https://github.com/MediaBrowser/Emby.Releases/releases/download"
PACKAGESSTAGE="aria2 unrar  uuid-runtime cpio jq rpm2cpio"
PACKAGESINTEL="intel-opencl-icd i965-va-driver gpg-agent libmfx1 ocl-icd-libopencl1"
INSTEMBY="rpm2cpio emby.rpm | cpio -i --make-directories"
BASEMLINK="mv -t /app/emby \\
     /tmp/opt/emby-server/system/* \\
     /tmp/opt/emby-server/lib/* \\
     /tmp/opt/emby-server/extra/lib/* \\
     /tmp/opt/emby-server/bin/ff* \\
     /tmp/opt/emby-server/etc"

## FINALIMAGE
FINALIMAGE="ghcr.io/linuxserver/baseimage-ubuntu:focal"
PACKAGESFINAL="aria2 jq unrar unzip curl uuid-runtime mesa-va-drivers"
PACKAGESINTEL="intel-opencl-icd i965-va-driver gpg-agent libmfx1 ocl-icd-libopencl1"
CLEANUP="apt-get remove -yqq aria2 jq software-properties-common gpg-agent && \\
     apt-get autoremove -yqq && apt-get clean -yqq && \\
     rm -rf /tmp/* /var/lib/apt/lists/* /var/tmp/"

PICTURE="./images/$APP.png"
APPFOLDER="./$FOLDER/$APP"
PORT="EXPOSE 8096 8920"
VOLUMEN="VOLUME /config"

### RELEASE SETTINGS ###

echo '{
   "appname": "'${APP}'",
   "apppic": "'${PICTURE}'",
   "appfolder": "./'$FOLDER'/'$APP'",
   "newversion": "'${NEWVERSION}'",
   "appbranch": "'${APPBRANCH}'",
   "baseimage": "'${BASEIMAGE}'",
   "description": "'${DESCRIPTION}'",
   "body": "Upgrading '${APP}' to '${NEWVERSION}'",
   "user": "github-actions[bot]"
}' > "./$FOLDER/$APP/release.json"

### DOCKER BUILD ###
### GENERATE Dockerfile based on release.json

echo '## This file is automatically generated (based on release.json)
##
## Do not changes any lines here
##
'"${HEADLINE}"'
FROM '"${BASESTAGE}"'

ARG TARGETPLATFORM
ARG BUILDPLATFORM
ARG VERSION="'"${NEWVERSION}"'"
ARG BRANCH="'"${APPBRANCH}"'"

ENV DEBIAN_FRONTEND="'"noninteractive"'"

RUN \
   echo "'"**** update runtime packages ****"'" && \
     '"${UPTCOMMAND}"' && \
   echo "'"**** install packages ****"'" && \
     '"${INSTCOMMAND}"' '"${PACKAGESSTAGE}"' && \
  echo "'"**** set arch for emby ****"'" && \
   case $TARGETPLATFORM in \
    "'"linux/amd64"'") export ARCH=x86_64 ;; \
    "'"linux/arm64"'") export ARCH=aarch64 ;; \
   esac \
   && \
  echo "'"**** install emby ****"'" && \
    mkdir -p /app/emby && \
    aria2c -d /tmp -o emby.rpm "'"${EMBY_URL}/"'${VERSION}'"/emby-server-rpm_"'${VERSION}'"_"'${ARCH}'".rpm"'" && \
    cd /tmp && '"${INSTEMBY}"' && \
    echo -e "'"UpdateMethod=docker\nBranch="'${BRANCH}'"\nPackageVersion="'${VERSION}'"\nPackageAuthor=[dockserver.io](https://dockserver.io)"'" > /app/package_info && \
  echo "'"**** unset arch ****"'" && \
    unset ARCH && \
  echo "'"**** cleanup ****"'" && \
    '"${BASEMLINK}"'

### FINALIMAGE
FROM  '"${FINALIMAGE}"'

ARG TARGETPLATFORM
ARG BUILDPLATFORM
ARG VERSION

ENV NVIDIA_DRIVER_CAPABILITIES="'""'" \
    DEBIAN_FRONTEND="'"noninteractive"'"

RUN \
   case $TARGETPLATFORM in \
    '"'linux/amd64'"') \
         export NVIDIA_DRIVER_CAPABILITIES="'"compute,video,utility"'" && \
     echo "'"**** add Intel repo ****"'" && \
         curl -sL https://repositories.intel.com/graphics/intel-graphics.key | apt-key add - && \
      echo "'"deb [arch=amd64] https://repositories.intel.com/graphics/ubuntu focal main"'" > /etc/apt/sources.list.d/intel.list && \
      export ARCH=amd64 && \
      echo "'"**** install runtime packages ****"'" && \
         '"${UPTCOMMAND}"' && \
      echo "'"**** install Intel packages ****"'" && \
         '"${INSTCOMMAND}"' '"${PACKAGESINTEL}"'; \
    ;; \
    '"'linux/arm64'"') export ARCH='arm64' && unset NVIDIA_DRIVER_CAPABILITIES ;; \
   esac \
   && \
   echo "'"**** install runtime packages ****"'" && \
     '"${UPTCOMMAND}"' && \
   echo "'"**** set permissions ****"'" && \
     usermod -d /app abc && \
  echo "'"**** cleanup ****"'" && \
     '"${CLEANUP}"'

COPY '"${BUILDSTAGE}"'
COPY --chown=abc '"${APPFOLDER}"'/root/ /

'"${PORT}"'

'"${VOLUMEN}"'
##EOF' > ./$FOLDER/$APP/Dockerfile
